FROM quay.io/wildfly/wildfly:latest-jdk17

COPY --chown=jboss:0 target/acmeair-mainservice-java-6.0.war /opt/jboss/wildfly/standalone/deployments/

CMD ["/opt/jboss/wildfly/bin/standalone.sh", "-c","standalone-microprofile.xml","-b", "0.0.0.0", "-bmanagement", "0.0.0.0","-Djboss.http.port=9080"]
