version: "3.9"

networks:
  my-net:
    name: my-net

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
    networks:
      - my-net
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_CREATE_TOPICS="rewards:1:1"
    networks:
      - my-net

  acmeair-booking-db:
    container_name: acmeair-booking-db
    image: mongo
    networks: 
      - my-net

  acmeair-customer-db:
    container_name: acmeair-customer-db
    image: mongo
    networks: 
      - my-net

  acmeair-flight-db:
    container_name: acmeair-flight-db
    image: mongo
    networks: 
      - my-net

  acmeair-nginx1:
    container_name: acmeair-nginx1
    networks: 
      - my-net
    restart: always
    build: ./nginx/
    ports:
      - "8080:80"
    volumes:
      - /www/public
    depends_on::
      - acmeair-mainservice-java
      - acmeair-authservice-java
      - acmeair-bookingservice-java
      - acmeair-customerservice-java
      - acmeair-flightservice-java

  acmeair-mainservice-java:
    container_name: acmeair-mainservice-java
    networks: 
      - my-net
    build: 
      context: ../acmeair-mainservice-java/
      dockerfile: Dockerfile
    environment:
      - LICENSE=accept
    mem_limit: 512m

  acmeair-authservice-java:
    container_name: acmeair-authservice-java
    networks: 
      - my-net
    build:
      context: ../acmeair-authservice-java/
      dockerfile: Dockerfile
    environment:
      - ACMEAIR_STACKAA_CUSTOMER_URL=http://acmeair-nginx1/customer
    mem_limit: 1g

  acmeair-bookingservice-java:
    container_name: acmeair-bookingservice-java
    networks: 
      - my-net
    build:
      context: ../acmeair-bookingservice-java/
      dockerfile: Dockerfile
    environment:
      - MONGO_HOST=acmeair-booking-db
      - ACMEAIR_STACKAA_AUTH_URL=http://acmeair-nginx1/auth
      - ACMEAIR_STACKAA_CUSTOMER_URL=http://acmeair-nginx1/customer
      - ACMEAIR_STACKAA_FLIGHT_URL=http://acmeair-nginx1/flight
    depends_on:
      - acmeair-booking-db
    mem_limit: 1g

  acmeair-customerservice-java:
    container_name: acmeair-customerservice-java
    networks: 
      - my-net
    build:
      context: ../acmeair-customerservice-java/
      dockerfile: Dockerfile
    environment:
      - MONGO_HOST=acmeair-customer-db
      - ACMEAIR_STACKAA_AUTH_URL=http://acmeair-nginx1/auth
    depends_on:
      - acmeair-customer-db
    mem_limit: 1g

  acmeair-flightservice-java:
    container_name: acmeair-flightservice-java
    networks: 
      - my-net
    build:
      context: ../acmeair-flightservice-java/
      dockerfile: Dockerfile
    environment:
      - MONGO_HOST=acmeair-flight-db
    depends_on:
      - acmeair-flight-db
    mem_limit: 1g








