version: "3.9"

networks:
  my-net:
    name: my-net

services:
  otel-lgtm:
    container_name: otel-lgtm
    image: grafana/otel-lgtm
    networks:
      - my-net
    ports:
      - "3000:3000" 
      - "4317:4317" 
      - "4318:4318"

  acmeair-booking-db:
    container_name: acmeair-booking-db
    image: docker.io/library/mongo:latest
    networks: 
      - my-net

  acmeair-customer-db:
    container_name: acmeair-customer-db
    image: docker.io/library/mongo:latest
    networks: 
      - my-net

  acmeair-flight-db:
    container_name: acmeair-flight-db
    image: docker.io/library/mongo:latest
    networks: 
      - my-net

  acmeair-nginx1:
    container_name: acmeair-nginx1
    networks: 
      - my-net
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    volumes:
      - /www/public
    depends_on:
      - acmeair-mainservice-java
      - acmeair-authservice-java
      - acmeair-bookingservice-java
      - acmeair-customerservice-java
      - acmeair-flightservice-java

  acmeair-mainservice-java:
    container_name: acmeair-mainservice-java
    networks: 
      - my-net
    build: 
      context: ../acmeair-mainservice-java/
      dockerfile: Dockerfile-daily
    environment:
      - LICENSE=accept
    mem_limit: 512m

  acmeair-authservice-java:
    container_name: acmeair-authservice-java
    networks: 
      - my-net
    build:
      context: ../acmeair-authservice-java/
      dockerfile: Dockerfile-daily
    environment:
      - ACMEAIR_STACKAA_CUSTOMER_URL=http://acmeair-nginx1/customer
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-lgtm:4317
      - OTEL_SERVICE_NAME=authservice
    mem_limit: 512m
    depends_on:
      - otel-lgtm

  acmeair-bookingservice-java:
    container_name: acmeair-bookingservice-java
    networks: 
      - my-net
    build:
      context: ../acmeair-bookingservice-java/
      dockerfile: Dockerfile-daily
    environment:
      - MONGO_HOST=acmeair-booking-db
      - ACMEAIR_STACKAA_AUTH_URL=http://acmeair-nginx1/auth
      - ACMEAIR_STACKAA_CUSTOMER_URL=http://acmeair-nginx1/customer
      - ACMEAIR_STACKAA_FLIGHT_URL=http://acmeair-nginx1/flight
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-lgtm:4317
      - OTEL_SERVICE_NAME=bookingservice
    depends_on:
      - otel-lgtm
      - acmeair-booking-db
    mem_limit: 512m

  acmeair-customerservice-java:
    container_name: acmeair-customerservice-java
    networks: 
      - my-net
    build:
      context: ../acmeair-customerservice-java/
      dockerfile: Dockerfile-daily
    environment:
      - MONGO_HOST=acmeair-customer-db
      - ACMEAIR_STACKAA_AUTH_URL=http://acmeair-nginx1/auth
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-lgtm:4317
      - OTEL_SERVICE_NAME=customerservice
    depends_on:
      - otel-lgtm
      - acmeair-customer-db
    mem_limit: 512m

  acmeair-flightservice-java:
    container_name: acmeair-flightservice-java
    networks: 
      - my-net
    build:
      context: ../acmeair-flightservice-java/
      dockerfile: Dockerfile-daily
    environment:
      - MONGO_HOST=acmeair-flight-db
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-lgtm:4317
      - OTEL_SERVICE_NAME=flightservice
    depends_on:
      - otel-lgtm
      - acmeair-flight-db
    mem_limit: 512m








