FROM websphere-liberty:microProfile2
# Install opentracing usr feature
RUN wget -t 10 -x -nd -P /opt/ibm/wlp/usr https://github.com/WASdev/sample.opentracing.zipkintracer/releases/download/1.3/liberty-opentracing-zipkintracer-1.3-sample.zip && cd /opt/ibm/wlp/usr && unzip liberty-opentracing-zipkintracer-1.3-sample.zip && rm liberty-opentracing-zipkintracer-1.3-sample.zip

COPY src/main/liberty/config/server.xml /config/server.xml
COPY /src/main/liberty/config/jvm.options.base /config/jvm.options
COPY /target/acmeair-mainservice-java-2.0.0-SNAPSHOT.war /config/apps/


# Don't fail on rc 22 feature already installed
RUN installUtility install --acceptLicense defaultServer || if [ $? -ne 22 ]; then exit $?; fi
