version: "3.9"

networks:
  my-net:

services:
  acmeair-nginx1:
    container_name: acmeair-nginx1
    networks: 
      - my-net
    restart: always
    build: ./nginx/
    ports:
      - "8080:80"
    volumes:
      - /www/public
    depends_on:
      - acmeair-mainservice-java
      - acmeair-authservice-java
      - acmeair-bookingservice-java
      - acmeair-customerservice-java
      - acmeair-flightservice-java

  acmeair-mainservice-java:
    container_name: acmeair-mainservice-java
    networks: 
      - my-net
    build: 
      context: ../acmeair-mainservice-java/
      dockerfile: Dockerfile
    cpuset: 0-1
    mem_limit: 1g

  acmeair-authservice-java:
    container_name: acmeair-authservice-java
    networks: 
      - my-net
    build:
      context: ../acmeair-authservice-java/
      dockerfile: Dockerfile-tm
    environment:
      - ACMEAIR_STACKAA_CUSTOMER_URL=http://acmeair-nginx1/customer
    cpuset: 2-3
    mem_limit: 1g


  acmeair-bookingservice-java:
    container_name: acmeair-bookingservice-java
    networks: 
      - my-net
    build:
      context: ../acmeair-bookingservice-java/
      dockerfile: Dockerfile-tm
    environment:
      - MONGO_HOST=192.168.122.1
      - ACMEAIR_STACKAA_AUTH_URL=http://acmeair-nginx1/auth
      - ACMEAIR_STACKAA_CUSTOMER_URL=http://acmeair-nginx1/customer
      - ACMEAIR_STACKAA_FLIGHT_URL=http://acmeair-nginx1/flight
    cpuset: 4-5
    mem_limit: 1g

  acmeair-customerservice-java:
    container_name: acmeair-customerservice-java
    networks: 
      - my-net
    build:
      context: ../acmeair-customerservice-java/
      dockerfile: Dockerfile-tm
    environment:
      - MONGO_HOST=192.168.122.1
      - ACMEAIR_STACKAA_AUTH_URL=http://acmeair-nginx1/auth
    cpuset: 6-7
    mem_limit: 1g

  acmeair-flightservice-java:
    container_name: acmeair-flightservice-java
    networks: 
      - my-net
    build:
      context: ../acmeair-flightservice-java/
      dockerfile: Dockerfile-tm
    environment:
      - MONGO_HOST=192.168.122.1
    cpuset: 8-9
    mem_limit: 1g
